# apiVersion: v1
# kind: Secret
# metadata:
#   creationTimestamp: 2020-01-22T18:41:56Z
#   name: mysecret
#   namespace: default
#   resourceVersion: "164619"
#   uid: cfee02d6-c137-11e5-8d73-42010af00002
# type: Opaque
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy
  mongo-password: bW9uZ29wYXNzd29yZA==